version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sns-dynamic-subscriber"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vuq5jvzma4ou"
s3_prefix = "sns-dynamic-subscriber"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamicSubTopicName=\"SNS-DynamicSubscription-Topic\""
